### ISSUE TITLE
not support apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by sbhnet** [k8spin/k8spin-operator#11]
root@master:~/k8spin-operator# kubectl apply -f ./deploy/crds/ -n default
unable to recognize "deploy/crds/organization.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/crds/space.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/crds/tenant.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

**Comment by sbhnet** [comment]
k8s 1.15.5 
kubectl api-versions

apiextensions.k8s.io/v1beta1

**Comment by angelbarrera92** [comment]
Hi @sbhnet,

K8Spin operator currently requires Kubernetes >= 1.16 version.
1.16 is the oldest one currently supported by the upstream Kubernetes project.
1.16 introduced `apiextensions.k8s.io/v1` source: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
