### ISSUE TITLE
Does this support boostrap token extraction ? 

### ISSUE THREAD

**Issue by knasim** [k8spin/k8spin-operator#23]
Can i retrieve the bootstrap token ?

**Comment by paurosello** [comment]
What do you mean by bootstrap token extraction?

**Comment by knasim** [comment]
sorry if i wasn't clearer, i meant extracting the default service account token ?

**Comment by paurosello** [comment]
For now we are not doing anything special with Authentication, we are only setting up the authorization part (RBAC).

We added support for Service Accounts recently https://github.com/k8spin/k8spin-operator/pull/16 and you should be able to use the service account token to interact with the cluster :)

**Comment by paurosello** [comment]
Does that solve your question?

**Comment by knasim** [comment]
Thank you !
