### ISSUE TITLE
Fails to create namespace for spaces...

### ISSUE THREAD

**Issue by Colorfingers** [k8spin/k8spin-operator#45]
### Is your feature request related to a problem? Please describe.
Following the example in the readme, I can create an org and a tenant however when I try to create a space I get the error:

**kubectl apply -f examples/space-1.yaml
Error from server (NotFound): error when creating "examples/space-1.yaml": namespaces "org-example-tenant-crm" not found**

The following shows the correct objects have been created.

**kubectl k8spin get org
Name                CPU                 Memory
example             10                   10G**

**kubectl k8spin get tenant
Organization        Name                CPU                 Memory
example                crm                    3                      3G**

### Describe the solution you'd like
I want to be able to create spaces to run pods in. Any suggestions?

### Describe alternatives you've considered
Kiosk, Kubeplus

**Comment by Colorfingers** [comment]
Reinstalled it and it works fine now! I think one of the pods was running but had issues... great idea and happy it's working!

**Comment by paurosello** [comment]
Do you have any logs in the operator?Also, could you list the namespaces that are available?Regards,PauEl 28 sept 2022, a las 4:04, Haptic Monkey ***@***.***> escribió:﻿
Is your feature request related to a problem? Please describe.
Following the example in the readme, I can create an org and a tenant however when I try to create a space I get the error:
kubectl apply -f examples/space-1.yaml Error from server (NotFound): error when creating "examples/space-1.yaml": namespaces "org-example-tenant-crm" not found
The following shows the correct objects have been created.
kubectl k8spin get org Name                CPU                 Memory example             10                   10G
kubectl k8spin get tenant Organization        Name                CPU                 Memory example                crm                    3                      3G
Describe the solution you'd like
I want to be able to create spaces to run pods in. Any suggestions?
Describe alternatives you've considered
Kiosk, Kubeplus
