### ISSUE TITLE
Prepare K8Spin Operator OSS

### ISSUE THREAD

**Issue by paurosello** [k8spin/k8spin-operator#7]
### Description

We need to stablish some contribution guidelines to let other users from the community collaborate in this project.

### Proposal

Add the basic pieces to proper contribute to the project like:

- LICENSE file
- CONTRIBUTING.md

#### Before

A developer does not know how to start writing code

#### After

A developer knows how to start writing code

#### Expected output

Everything ready to start developing

**Comment by angelbarrera92** [comment]
Closed with #20
